export default {
	responses: [
		{ index: 1, value: true },
		{ index: 2, value: true },
		{ index: 3, value: false },
		{ index: 4, value: true },
		{ index: 5, value: true },
		{ index: 6, value: true },
		{ index: 7, value: true },
		{ index: 8, value: true },
		{ index: 9, value: true },
		{ index: 10, value: true },
		{ index: 11, value: false },
		{ index: 12, value: true },
		{ index: 13, value: true },
		{ index: 14, value: false },
		{ index: 15, value: true },
		{ index: 16, value: false },
		{ index: 17, value: true },
		{ index: 18, value: false },
		{ index: 19, value: true },
		{ index: 20, value: false },
		{ index: 21, value: false },
		{ index: 22, value: false },
		{ index: 23, value: false },
		{ index: 24, value: true },
		{ index: 25, value: true },
		{ index: 26, value: false },
		{ index: 27, value: true },
		{ index: 28, value: false },
		{ index: 29, value: false },
		{ index: 30, value: false },
		{ index: 31, value: false },
		{ index: 32, value: true },
		{ index: 33, value: false },
		{ index: 34, value: true },
		{ index: 35, value: true },
		{ index: 36, value: false },
		{ index: 37, value: true },
		{ index: 38, value: false },
		{ index: 39, value: false },
		{ index: 40, value: true },
		{ index: 41, value: false },
		{ index: 42, value: false },
		{ index: 43, value: true },
		{ index: 44, value: true },
		{ index: 45, value: false },
		{ index: 46, value: false },
		{ index: 47, value: false },
		{ index: 48, value: false },
		{ index: 49, value: false },
		{ index: 50, value: false },
		{ index: 51, value: true },
		{ index: 52, value: true },
		{ index: 53, value: true },
		{ index: 54, value: false },
		{ index: 55, value: false },
		{ index: 56, value: true },
		{ index: 57, value: false },
		{ index: 58, value: false },
		{ index: 59, value: false },
		{ index: 60, value: true },
		{ index: 61, value: true },
		{ index: 62, value: false },
		{ index: 63, value: true },
		{ index: 64, value: true },
		{ index: 65, value: false },
		{ index: 66, value: false },
		{ index: 67, value: true },
		{ index: 68, value: true },
		{ index: 69, value: false },
		{ index: 70, value: false },
		{ index: 71, value: true },
		{ index: 72, value: true },
		{ index: 73, value: true },
		{ index: 74, value: false },
		{ index: 75, value: false },
		{ index: 76, value: false },
		{ index: 77, value: true },
		{ index: 78, value: false },
		{ index: 79, value: false },
		{ index: 80, value: true },
		{ index: 81, value: true },
		{ index: 82, value: false },
		{ index: 83, value: false },
		{ index: 84, value: true },
		{ index: 85, value: true },
		{ index: 86, value: true },
		{ index: 87, value: false },
		{ index: 88, value: true },
		{ index: 89, value: true },
		{ index: 90, value: true },
	],
	result: {
		psychoticism: 6,
		neuroticism: 12,
		extraversion: 15,
		'lie-scale': 9,
	},
};