export default {
	responses: [
		{ index: 1, value: true },
		{ index: 2, value: true },
		{ index: 3, value: true },
		{ index: 4, value: true },
		{ index: 5, value: false },
		{ index: 6, value: false },
		{ index: 7, value: true },
		{ index: 8, value: false },
		{ index: 9, value: false },
		{ index: 10, value: true },
		{ index: 11, value: false },
		{ index: 12, value: false },
		{ index: 13, value: true },
		{ index: 14, value: false },
		{ index: 15, value: false },
		{ index: 16, value: false },
		{ index: 17, value: false },
		{ index: 18, value: false },
		{ index: 19, value: true },
		{ index: 20, value: true },
		{ index: 21, value: false },
		{ index: 22, value: false },
		{ index: 23, value: false },
		{ index: 24, value: false },
		{ index: 25, value: true },
		{ index: 26, value: true },
		{ index: 27, value: true },
		{ index: 28, value: true },
		{ index: 29, value: false },
		{ index: 30, value: false },
		{ index: 31, value: true },
		{ index: 32, value: true },
		{ index: 33, value: false },
		{ index: 34, value: false },
		{ index: 35, value: true },
		{ index: 36, value: false },
		{ index: 37, value: false },
		{ index: 38, value: false },
		{ index: 39, value: false },
		{ index: 40, value: false },
		{ index: 41, value: false },
		{ index: 42, value: true },
		{ index: 43, value: true },
		{ index: 44, value: true },
		{ index: 45, value: true },
		{ index: 46, value: true },
		{ index: 47, value: true },
		{ index: 48, value: false },
		{ index: 49, value: false },
		{ index: 50, value: false },
		{ index: 51, value: false },
		{ index: 52, value: true },
		{ index: 53, value: true },
		{ index: 54, value: false },
		{ index: 55, value: false },
		{ index: 56, value: true },
		{ index: 57, value: false },
		{ index: 58, value: false },
		{ index: 59, value: false },
		{ index: 60, value: false },
		{ index: 61, value: true },
		{ index: 62, value: false },
		{ index: 63, value: true },
		{ index: 64, value: true },
		{ index: 65, value: true },
		{ index: 66, value: false },
		{ index: 67, value: false },
		{ index: 68, value: false },
		{ index: 69, value: true },
		{ index: 70, value: true },
		{ index: 71, value: true },
		{ index: 72, value: false },
		{ index: 73, value: true },
		{ index: 74, value: true },
		{ index: 75, value: true },
		{ index: 76, value: false },
		{ index: 77, value: true },
		{ index: 78, value: true },
		{ index: 79, value: false },
		{ index: 80, value: true },
		{ index: 81, value: true },
		{ index: 82, value: true },
		{ index: 83, value: true },
		{ index: 84, value: false },
		{ index: 85, value: false },
		{ index: 86, value: false },
		{ index: 87, value: false },
		{ index: 88, value: true },
		{ index: 89, value: true },
		{ index: 90, value: false },
		{ index: 91, value: false },
		{ index: 92, value: true },
		{ index: 93, value: false },
		{ index: 94, value: false },
		{ index: 95, value: false },
		{ index: 96, value: false },
		{ index: 97, value: false },
		{ index: 98, value: true },
		{ index: 99, value: true },
		{ index: 100, value: true },
		{ index: 101, value: false },
		{ index: 102, value: false },
		{ index: 103, value: true },
		{ index: 104, value: true },
		{ index: 105, value: true },
		{ index: 106, value: true },
		{ index: 107, value: true },
		{ index: 108, value: false },
	],
	result: {
		'novelty-seeking': 11,
		'harm-avoidance': 7,
		'reward-dependence': 5,
		persistence: 1,
		'self-directedness': 10,
		cooperativeness: 13,
		'self-transcendence-(1)': 3,
		'self-transcendence-(2)': 3,
		validity: 3,
	},
};
