export default {
	responses: [
		{ index: 1, value: true },
		{ index: 2, value: true },
		{ index: 3, value: false },
		{ index: 4, value: true },
		{ index: 5, value: false },
		{ index: 6, value: false },
		{ index: 7, value: false },
		{ index: 8, value: true },
		{ index: 9, value: false },
		{ index: 10, value: true },
		{ index: 11, value: false },
		{ index: 12, value: true },
		{ index: 13, value: false },
		{ index: 14, value: false },
		{ index: 15, value: true },
		{ index: 16, value: false },
		{ index: 17, value: false },
		{ index: 18, value: true },
		{ index: 19, value: false },
		{ index: 20, value: true },
		{ index: 21, value: true },
		{ index: 22, value: false },
		{ index: 23, value: true },
		{ index: 24, value: true },
		{ index: 25, value: true },
		{ index: 26, value: false },
		{ index: 27, value: false },
		{ index: 28, value: false },
		{ index: 29, value: false },
		{ index: 30, value: false },
		{ index: 31, value: false },
		{ index: 32, value: false },
		{ index: 33, value: false },
		{ index: 34, value: false },
		{ index: 35, value: false },
		{ index: 36, value: true },
		{ index: 37, value: false },
		{ index: 38, value: false },
		{ index: 39, value: true },
		{ index: 40, value: false },
		{ index: 41, value: true },
		{ index: 42, value: false },
		{ index: 43, value: false },
		{ index: 44, value: false },
		{ index: 45, value: true },
		{ index: 46, value: false },
		{ index: 47, value: false },
		{ index: 48, value: false },
		{ index: 49, value: true },
		{ index: 50, value: true },
		{ index: 51, value: true },
		{ index: 52, value: false },
		{ index: 53, value: true },
		{ index: 54, value: false },
		{ index: 55, value: true },
		{ index: 56, value: true },
		{ index: 57, value: true },
		{ index: 58, value: false },
		{ index: 59, value: false },
		{ index: 60, value: false },
		{ index: 61, value: true },
		{ index: 62, value: false },
		{ index: 63, value: false },
		{ index: 64, value: false },
		{ index: 65, value: false },
		{ index: 66, value: false },
		{ index: 67, value: true },
		{ index: 68, value: true },
		{ index: 69, value: false },
		{ index: 70, value: true },
		{ index: 71, value: false },
		{ index: 72, value: false },
		{ index: 73, value: true },
		{ index: 74, value: true },
		{ index: 75, value: false },
		{ index: 76, value: true },
		{ index: 77, value: true },
		{ index: 78, value: false },
		{ index: 79, value: false },
		{ index: 80, value: false },
		{ index: 81, value: false },
		{ index: 82, value: false },
		{ index: 83, value: false },
		{ index: 84, value: false },
		{ index: 85, value: false },
		{ index: 86, value: true },
		{ index: 87, value: false },
		{ index: 88, value: false },
		{ index: 89, value: false },
		{ index: 90, value: false },
		{ index: 91, value: false },
		{ index: 92, value: true },
		{ index: 93, value: true },
		{ index: 94, value: false },
		{ index: 95, value: false },
		{ index: 96, value: true },
		{ index: 97, value: false },
		{ index: 98, value: false },
		{ index: 99, value: false },
		{ index: 100, value: false },
		{ index: 101, value: true },
		{ index: 102, value: false },
		{ index: 103, value: true },
		{ index: 104, value: true },
		{ index: 105, value: false },
		{ index: 106, value: false },
		{ index: 107, value: false },
		{ index: 108, value: true },
		{ index: 109, value: false },
		{ index: 110, value: false },
		{ index: 111, value: false },
		{ index: 112, value: false },
		{ index: 113, value: false },
		{ index: 114, value: false },
		{ index: 115, value: false },
		{ index: 116, value: false },
		{ index: 117, value: true },
		{ index: 118, value: false },
		{ index: 119, value: false },
		{ index: 120, value: false },
		{ index: 121, value: false },
		{ index: 122, value: false },
		{ index: 123, value: false },
		{ index: 124, value: false },
		{ index: 125, value: false },
		{ index: 126, value: false },
		{ index: 127, value: false },
		{ index: 128, value: false },
		{ index: 129, value: false },
		{ index: 130, value: true },
		{ index: 131, value: true },
		{ index: 132, value: false },
		{ index: 133, value: false },
		{ index: 134, value: false },
		{ index: 135, value: false },
		{ index: 136, value: false },
		{ index: 137, value: false },
		{ index: 138, value: false },
		{ index: 139, value: false },
		{ index: 140, value: false },
		{ index: 141, value: false },
		{ index: 142, value: false },
		{ index: 143, value: false },
		{ index: 144, value: false },
		{ index: 145, value: true },
		{ index: 146, value: true },
		{ index: 147, value: false },
		{ index: 148, value: true },
		{ index: 149, value: true },
		{ index: 150, value: false },
		{ index: 151, value: false },
		{ index: 152, value: false },
		{ index: 153, value: false },
		{ index: 154, value: false },
		{ index: 155, value: true },
		{ index: 156, value: false },
		{ index: 157, value: false },
		{ index: 158, value: false },
		{ index: 159, value: true },
		{ index: 160, value: false },
	],
	result: {
		'introversive': 18,
		'inhibited': 8,
		'doleful': 5,
		'submissive': 33,
		'dramatizing': 54,
		'egoistic': 49,
		'unruly': 46,
		'forceful': 21,
		'conforming': 43,
		'oppositional': 24,
		'self-demeaning': 11,
		'borderline-tendency': 10,
		'identity-diffusion': 12,
		'self-devaluation': 8,
		'body-disapproval': 0,
		'sexual-discomfort': 34,
		'peer-insecurity': 3,
		'social-insensitivity': 39,
		'family-discord': 28,
		'childhood-abuse': 2,
		'eating-dysfunctions': 0,
		'substance-abuse-proneness': 21,
		'delinquent-predisposition': 35,
		'impulsive-propensity': 29,
		'anxious-feelings': 21,
		'depressive-affect': 5,
		'suicidal-tendency': 2,
		'desirability': 15,
		'debasement': 1,
		'reliability': 0,
	},
};