export default {
	responses: [
		{ "index": 1, "value": false },
		{ "index": 2, "value": true },
		{ "index": 3, "value": false },
		{ "index": 4, "value": false },
		{ "index": 5, "value": true },
		{ "index": 6, "value": false },
		{ "index": 7, "value": true },
		{ "index": 8, "value": true },
		{ "index": 9, "value": false },
		{ "index": 10, "value": true },
		{ "index": 11, "value": false },
		{ "index": 12, "value": true },
		{ "index": 13, "value": true },
		{ "index": 14, "value": false },
		{ "index": 15, "value": false },
		{ "index": 16, "value": true },
		{ "index": 17, "value": false },
		{ "index": 18, "value": true },
		{ "index": 19, "value": false },
		{ "index": 20, "value": false },
		{ "index": 21, "value": false },
		{ "index": 22, "value": true },
		{ "index": 23, "value": true },
		{ "index": 24, "value": true },
		{ "index": 25, "value": false },
		{ "index": 26, "value": true },
		{ "index": 27, "value": true },
		{ "index": 28, "value": true },
		{ "index": 29, "value": true },
		{ "index": 30, "value": true },
		{ "index": 31, "value": false },
		{ "index": 32, "value": true },
		{ "index": 33, "value": false },
		{ "index": 34, "value": false },
		{ "index": 35, "value": true },
		{ "index": 36, "value": true },
		{ "index": 37, "value": false },
		{ "index": 38, "value": false },
		{ "index": 39, "value": true },
		{ "index": 40, "value": true },
		{ "index": 41, "value": true },
		{ "index": 42, "value": false },
		{ "index": 43, "value": false },
		{ "index": 44, "value": true },
		{ "index": 45, "value": true },
		{ "index": 46, "value": true },
		{ "index": 47, "value": false },
		{ "index": 48, "value": true },
		{ "index": 49, "value": false },
		{ "index": 50, "value": true },
		{ "index": 51, "value": true },
		{ "index": 52, "value": true },
		{ "index": 53, "value": false },
		{ "index": 54, "value": false },
		{ "index": 55, "value": true },
		{ "index": 56, "value": true },
		{ "index": 57, "value": false },
		{ "index": 58, "value": true },
		{ "index": 59, "value": true },
		{ "index": 60, "value": true },
		{ "index": 61, "value": true },
		{ "index": 62, "value": true },
		{ "index": 63, "value": true },
		{ "index": 64, "value": true },
		{ "index": 65, "value": true },
		{ "index": 66, "value": false },
		{ "index": 67, "value": true },
		{ "index": 68, "value": true },
		{ "index": 69, "value": false },
		{ "index": 70, "value": true },
		{ "index": 71, "value": true },
		{ "index": 72, "value": true },
		{ "index": 73, "value": false },
		{ "index": 74, "value": true },
		{ "index": 75, "value": false },
		{ "index": 76, "value": false },
		{ "index": 77, "value": true },
		{ "index": 78, "value": true },
		{ "index": 79, "value": false },
		{ "index": 80, "value": false },
		{ "index": 81, "value": true },
		{ "index": 82, "value": true },
		{ "index": 83, "value": false },
		{ "index": 84, "value": false },
		{ "index": 85, "value": false },
		{ "index": 86, "value": false },
		{ "index": 87, "value": false },
		{ "index": 88, "value": true },
		{ "index": 89, "value": true },
		{ "index": 90, "value": false },
		{ "index": 91, "value": true },
		{ "index": 92, "value": false },
		{ "index": 93, "value": true },
		{ "index": 94, "value": false },
		{ "index": 95, "value": true },
		{ "index": 96, "value": false },
		{ "index": 97, "value": false },
		{ "index": 98, "value": false },
		{ "index": 99, "value": true },
		{ "index": 100, "value": true },
		{ "index": 101, "value": true },
		{ "index": 102, "value": false },
		{ "index": 103, "value": true },
		{ "index": 104, "value": true },
		{ "index": 105, "value": false },
		{ "index": 106, "value": false },
		{ "index": 107, "value": false },
		{ "index": 108, "value": true },
		{ "index": 109, "value": false },
		{ "index": 110, "value": true },
		{ "index": 111, "value": false },
		{ "index": 112, "value": false },
		{ "index": 113, "value": true },
		{ "index": 114, "value": true },
		{ "index": 115, "value": true },
		{ "index": 116, "value": true },
		{ "index": 117, "value": true },
		{ "index": 118, "value": false },
		{ "index": 119, "value": true },
		{ "index": 120, "value": true },
		{ "index": 121, "value": false },
		{ "index": 122, "value": false },
		{ "index": 123, "value": true },
		{ "index": 124, "value": false },
		{ "index": 125, "value": true },
		{ "index": 126, "value": false },
		{ "index": 127, "value": true },
		{ "index": 128, "value": true },
		{ "index": 129, "value": false },
		{ "index": 130, "value": true },
		{ "index": 131, "value": false },
		{ "index": 132, "value": true },
		{ "index": 133, "value": false },
		{ "index": 134, "value": false },
		{ "index": 135, "value": true },
		{ "index": 136, "value": false },
		{ "index": 137, "value": true },
		{ "index": 138, "value": true },
		{ "index": 139, "value": false },
		{ "index": 140, "value": false },
		{ "index": 141, "value": false },
		{ "index": 142, "value": false },
		{ "index": 143, "value": true },
		{ "index": 144, "value": true },
		{ "index": 145, "value": false },
		{ "index": 146, "value": true },
		{ "index": 147, "value": true },
		{ "index": 148, "value": false },
		{ "index": 149, "value": true },
		{ "index": 150, "value": false },
		{ "index": 151, "value": false },
		{ "index": 152, "value": true },
		{ "index": 153, "value": false },
		{ "index": 154, "value": false },
		{ "index": 155, "value": false },
		{ "index": 156, "value": true },
		{ "index": 157, "value": true },
		{ "index": 158, "value": true },
		{ "index": 159, "value": false },
		{ "index": 160, "value": false },
		{ "index": 161, "value": false },
		{ "index": 162, "value": true },
		{ "index": 163, "value": false },
		{ "index": 164, "value": true },
		{ "index": 165, "value": false },
		{ "index": 166, "value": false },
		{ "index": 167, "value": true },
		{ "index": 168, "value": true },
		{ "index": 169, "value": true },
		{ "index": 170, "value": false },
		{ "index": 171, "value": true },
		{ "index": 172, "value": false },
		{ "index": 173, "value": true },
		{ "index": 174, "value": false },
		{ "index": 175, "value": false },
		{ "index": 176, "value": false },
		{ "index": 177, "value": true },
		{ "index": 178, "value": false },
		{ "index": 179, "value": false },
		{ "index": 180, "value": false },
		{ "index": 181, "value": false },
		{ "index": 182, "value": false },
		{ "index": 183, "value": true },
		{ "index": 184, "value": true },
		{ "index": 185, "value": false },
		{ "index": 186, "value": true },
		{ "index": 187, "value": true },
		{ "index": 188, "value": false },
		{ "index": 189, "value": false },
		{ "index": 190, "value": true },
		{ "index": 191, "value": true },
		{ "index": 192, "value": false },
		{ "index": 193, "value": false },
		{ "index": 194, "value": true },
		{ "index": 195, "value": false },
		{ "index": 196, "value": false },
		{ "index": 197, "value": true },
		{ "index": 198, "value": true },
		{ "index": 199, "value": false },
		{ "index": 200, "value": false },
		{ "index": 201, "value": false },
		{ "index": 202, "value": false },
		{ "index": 203, "value": false },
		{ "index": 204, "value": true },
		{ "index": 205, "value": false },
		{ "index": 206, "value": false },
		{ "index": 207, "value": false },
		{ "index": 208, "value": false },
		{ "index": 209, "value": true },
		{ "index": 210, "value": false },
		{ "index": 211, "value": true },
		{ "index": 212, "value": false },
		{ "index": 213, "value": true },
		{ "index": 214, "value": true },
		{ "index": 215, "value": true },
		{ "index": 216, "value": false },
		{ "index": 217, "value": false },
		{ "index": 218, "value": false },
		{ "index": 219, "value": false },
		{ "index": 220, "value": true },
		{ "index": 221, "value": true },
		{ "index": 222, "value": false },
		{ "index": 223, "value": false },
		{ "index": 224, "value": true },
		{ "index": 225, "value": false },
		{ "index": 226, "value": false },
		{ "index": 227, "value": true },
		{ "index": 228, "value": true },
		{ "index": 229, "value": false },
		{ "index": 230, "value": false },
		{ "index": 231, "value": false },
		{ "index": 232, "value": true },
		{ "index": 233, "value": true },
		{ "index": 234, "value": false },
		{ "index": 235, "value": true },
		{ "index": 236, "value": false },
		{ "index": 237, "value": false },
		{ "index": 238, "value": false },
		{ "index": 239, "value": true },
		{ "index": 240, "value": false },
		{ "index": 241, "value": false },
		{ "index": 242, "value": false },
		{ "index": 243, "value": true },
		{ "index": 244, "value": true },
		{ "index": 245, "value": false },
		{ "index": 246, "value": true },
		{ "index": 247, "value": true },
		{ "index": 248, "value": true },
		{ "index": 249, "value": false },
		{ "index": 250, "value": false },
		{ "index": 251, "value": false },
		{ "index": 252, "value": false },
		{ "index": 253, "value": false },
		{ "index": 254, "value": true },
		{ "index": 255, "value": false },
		{ "index": 256, "value": true },
		{ "index": 257, "value": true },
		{ "index": 258, "value": false },
		{ "index": 259, "value": false },
		{ "index": 260, "value": true },
		{ "index": 261, "value": true },
		{ "index": 262, "value": false },
		{ "index": 263, "value": true },
		{ "index": 264, "value": true },
		{ "index": 265, "value": true },
		{ "index": 266, "value": false },
		{ "index": 267, "value": false },
		{ "index": 268, "value": false },
		{ "index": 269, "value": true },
		{ "index": 270, "value": false },
		{ "index": 271, "value": true },
		{ "index": 272, "value": true },
		{ "index": 273, "value": false },
		{ "index": 274, "value": true },
		{ "index": 275, "value": true },
		{ "index": 276, "value": true },
		{ "index": 277, "value": false },
		{ "index": 278, "value": true },
		{ "index": 279, "value": false },
		{ "index": 280, "value": false },
		{ "index": 281, "value": true },
		{ "index": 282, "value": false },
		{ "index": 283, "value": true },
		{ "index": 284, "value": true },
		{ "index": 285, "value": false },
		{ "index": 286, "value": true },
		{ "index": 287, "value": false },
		{ "index": 288, "value": false },
		{ "index": 289, "value": false },
		{ "index": 290, "value": false },
		{ "index": 291, "value": false },
		{ "index": 292, "value": true },
		{ "index": 293, "value": false },
		{ "index": 294, "value": false },
		{ "index": 295, "value": false },
		{ "index": 296, "value": false },
		{ "index": 297, "value": false },
		{ "index": 298, "value": true },
		{ "index": 299, "value": true },
		{ "index": 300, "value": false },
		{ "index": 301, "value": false },
		{ "index": 302, "value": true },
		{ "index": 303, "value": true },
		{ "index": 304, "value": false },
		{ "index": 305, "value": true },
		{ "index": 306, "value": false },
		{ "index": 307, "value": true },
		{ "index": 308, "value": false },
		{ "index": 309, "value": false },
		{ "index": 310, "value": true },
		{ "index": 311, "value": true },
		{ "index": 312, "value": false },
		{ "index": 313, "value": true },
		{ "index": 314, "value": false },
		{ "index": 315, "value": true },
		{ "index": 316, "value": true },
		{ "index": 317, "value": false },
		{ "index": 318, "value": true },
		{ "index": 319, "value": true },
		{ "index": 320, "value": true },
		{ "index": 321, "value": true },
		{ "index": 322, "value": true },
		{ "index": 323, "value": false },
		{ "index": 324, "value": true },
		{ "index": 325, "value": true },
		{ "index": 326, "value": false },
		{ "index": 327, "value": true },
		{ "index": 328, "value": true },
		{ "index": 329, "value": true },
		{ "index": 330, "value": false },
		{ "index": 331, "value": true },
		{ "index": 332, "value": true },
		{ "index": 333, "value": false },
		{ "index": 334, "value": false },
		{ "index": 335, "value": true },
		{ "index": 336, "value": true },
		{ "index": 337, "value": true },
		{ "index": 338, "value": true }],
	result: {
		// Validity Scales
		'VRINr': 0,
		'TRINr': 11,
		'Fr': 18,
		'Fpr': 5,
		'Fs': 1,
		'FBSr': 12,
		'Lr': 3,
		'Kr': 1,
		// HO Scales
		'EID': 36,
		'THD': 10,
		'BXD': 6,
		// RC Scales
		'RCd': 21,
		'RC1': 7,
		'RC2': 14,
		'RC3': 7,
		'RC4': 9,
		'RC6': 9,
		'RC7': 18,
		'RC8': 6,
		'RC9': 13,
		// SOM Scales
		'MLS': 8,
		'GIC': 0,
		'HPC': 3,
		'NUC': 1,
		'COG': 2,
		// Internalize Scales
		'SUI': 3,
		'HLP': 5,
		'SFD': 3,
		'NFC': 8,
		'STW': 6,
		'AXY': 3,
		'ANP': 6,
		'BRF': 3,
		'MSF': 1,
		// Externalize Scales
		'JCP': 0,
		'SUB': 1,
		'AGG': 6,
		'ACT': 2,
		// INPER Scales
		'FML': 8,
		'IPP': 1,
		'SAV': 10,
		'SHY': 6,
		'DSF': 1,
		// Interest Scales
		'AES': 2,
		'MEC': 0,
		// PSY5 Scales
		'AGGRr': 13,
		'PSYCr': 10,
		'DISCr': 4,
		'NEGEr': 15,
		'INTRr': 18,
	},
};
