export default {
	responses: [
		{ index: 1, value: false },
		{ index: 2, value: true },
		{ index: 3, value: true },
		{ index: 4, value: false },
		{ index: 5, value: true },
		{ index: 6, value: false },
		{ index: 7, value: true },
		{ index: 8, value: true },
		{ index: 9, value: true },
		{ index: 10, value: false },
		{ index: 11, value: true },
		{ index: 12, value: true },
		{ index: 13, value: true },
		{ index: 14, value: false },
		{ index: 15, value: false },
		{ index: 16, value: false },
		{ index: 17, value: true },
		{ index: 18, value: true },
		{ index: 19, value: true },
		{ index: 20, value: false },
		{ index: 21, value: true },
		{ index: 22, value: false },
		{ index: 23, value: true },
		{ index: 24, value: true },
		{ index: 25, value: false },
		{ index: 26, value: false },
		{ index: 27, value: true },
		{ index: 28, value: true },
		{ index: 29, value: true },
		{ index: 30, value: false },
		{ index: 31, value: false },
		{ index: 32, value: true },
		{ index: 33, value: true },
		{ index: 34, value: true },
		{ index: 35, value: false },
		{ index: 36, value: true },
		{ index: 37, value: false },
		{ index: 38, value: true },
		{ index: 39, value: true },
		{ index: 40, value: false },
		{ index: 41, value: true },
		{ index: 42, value: false },
		{ index: 43, value: true },
		{ index: 44, value: false },
		{ index: 45, value: true },
		{ index: 46, value: true },
		{ index: 47, value: false },
		{ index: 48, value: true },
		{ index: 49, value: false },
		{ index: 50, value: true },
		{ index: 51, value: true },
		{ index: 52, value: true },
		{ index: 53, value: true },
		{ index: 54, value: true },
		{ index: 55, value: true },
		{ index: 56, value: false },
		{ index: 57, value: true },
		{ index: 58, value: false },
		{ index: 59, value: true },
		{ index: 60, value: true },
		{ index: 61, value: true },
		{ index: 62, value: true },
		{ index: 63, value: true },
		{ index: 64, value: true },
		{ index: 65, value: true },
		{ index: 66, value: true },
		{ index: 67, value: false },
		{ index: 68, value: true },
		{ index: 69, value: true },
		{ index: 70, value: true },
		{ index: 71, value: true },
		{ index: 72, value: true },
		{ index: 73, value: true },
		{ index: 74, value: true },
		{ index: 75, value: true },
		{ index: 76, value: true },
		{ index: 77, value: false },
		{ index: 78, value: true },
		{ index: 79, value: true },
		{ index: 80, value: false },
		{ index: 81, value: true },
		{ index: 82, value: true },
		{ index: 83, value: true },
		{ index: 84, value: true },
		{ index: 85, value: true },
		{ index: 86, value: false },
		{ index: 87, value: false },
		{ index: 88, value: true },
		{ index: 89, value: true },
		{ index: 90, value: false },
		{ index: 91, value: true },
		{ index: 92, value: true },
		{ index: 93, value: true },
		{ index: 94, value: true },
		{ index: 95, value: true },
		{ index: 96, value: false },
		{ index: 97, value: true },
		{ index: 98, value: true },
		{ index: 99, value: false },
		{ index: 100, value: true },
	],
	result: {
		anxiety: 16,
		hysteria: 7,
		paranoia: 12,
		mania: 10,
		depression: 9,
		schizophrenia: 14,
		'repressive-sensitization': 14,
		'personality-disorder': 25,
		'k-(lie)': 3,
	},
};
