export default {
	responses: [
		{ index: 1, value: false },
		{ index: 2, value: true },
		{ index: 3, value: true },
		{ index: 4, value: true },
		{ index: 5, value: true },
		{ index: 6, value: true },
		{ index: 7, value: false },
		{ index: 8, value: false },
		{ index: 9, value: false },
		{ index: 10, value: true },
		{ index: 11, value: false },
		{ index: 12, value: false },
		{ index: 13, value: true },
		{ index: 14, value: true },
		{ index: 15, value: false },
		{ index: 16, value: false },
		{ index: 17, value: true },
		{ index: 18, value: false },
		{ index: 19, value: true },
		{ index: 20, value: false },
		{ index: 21, value: true },
		{ index: 22, value: false },
		{ index: 23, value: false },
		{ index: 24, value: false },
		{ index: 25, value: true },
		{ index: 26, value: false },
		{ index: 27, value: true },
		{ index: 28, value: true },
		{ index: 29, value: false },
		{ index: 30, value: false },
		{ index: 31, value: false },
		{ index: 32, value: true },
		{ index: 33, value: false },
		{ index: 34, value: false },
		{ index: 35, value: false },
		{ index: 36, value: true },
		{ index: 37, value: true },
		{ index: 38, value: true },
		{ index: 39, value: true },
		{ index: 40, value: true },
		{ index: 41, value: true },
		{ index: 42, value: true },
		{ index: 43, value: false },
		{ index: 44, value: true },
		{ index: 45, value: true },
		{ index: 46, value: false },
		{ index: 47, value: true },
		{ index: 48, value: false },
		{ index: 49, value: false },
		{ index: 50, value: true },
		{ index: 51, value: false },
		{ index: 52, value: true },
		{ index: 53, value: true },
		{ index: 54, value: false },
		{ index: 55, value: true },
		{ index: 56, value: true },
		{ index: 57, value: false },
		{ index: 58, value: true },
		{ index: 59, value: true },
		{ index: 60, value: true },
		{ index: 61, value: false },
		{ index: 62, value: false },
		{ index: 63, value: false },
		{ index: 64, value: true },
		{ index: 65, value: true },
		{ index: 66, value: false },
		{ index: 67, value: false },
		{ index: 68, value: false },
		{ index: 69, value: true },
		{ index: 70, value: true },
		{ index: 71, value: false },
		{ index: 72, value: true },
		{ index: 73, value: true },
		{ index: 74, value: true },
		{ index: 75, value: true },
		{ index: 76, value: false },
		{ index: 77, value: false },
		{ index: 78, value: true },
		{ index: 79, value: true },
		{ index: 80, value: true },
		{ index: 81, value: false },
		{ index: 82, value: true },
		{ index: 83, value: true },
		{ index: 84, value: false },
		{ index: 85, value: false },
		{ index: 86, value: false },
		{ index: 87, value: true },
		{ index: 88, value: true },
		{ index: 89, value: true },
		{ index: 90, value: true },
		{ index: 91, value: false },
		{ index: 92, value: false },
		{ index: 93, value: true },
		{ index: 94, value: true },
		{ index: 95, value: true },
		{ index: 96, value: true },
		{ index: 97, value: false },
		{ index: 98, value: false },
		{ index: 99, value: false },
		{ index: 100, value: true },
		{ index: 101, value: true },
		{ index: 102, value: true },
		{ index: 103, value: true },
		{ index: 104, value: false },
		{ index: 105, value: false },
		{ index: 106, value: true },
		{ index: 107, value: false },
		{ index: 108, value: true },
		{ index: 109, value: false },
		{ index: 110, value: false },
		{ index: 111, value: true },
		{ index: 112, value: true },
		{ index: 113, value: true },
		{ index: 114, value: true },
		{ index: 115, value: true },
		{ index: 116, value: false },
		{ index: 117, value: true },
		{ index: 118, value: true },
		{ index: 119, value: true },
		{ index: 120, value: false },
		{ index: 121, value: false },
		{ index: 122, value: true },
		{ index: 123, value: true },
		{ index: 124, value: false },
		{ index: 125, value: false },
		{ index: 126, value: true },
		{ index: 127, value: true },
		{ index: 128, value: true },
		{ index: 129, value: true },
		{ index: 130, value: true },
		{ index: 131, value: true },
		{ index: 132, value: true },
		{ index: 133, value: true },
		{ index: 134, value: true },
		{ index: 135, value: true },
		{ index: 136, value: false },
		{ index: 137, value: true },
		{ index: 138, value: false },
		{ index: 139, value: false },
		{ index: 140, value: true },
		{ index: 141, value: true },
		{ index: 142, value: false },
		{ index: 143, value: false },
		{ index: 144, value: false },
		{ index: 145, value: true },
		{ index: 146, value: false },
		{ index: 147, value: false },
		{ index: 148, value: true },
		{ index: 149, value: true },
		{ index: 150, value: false },
		{ index: 151, value: true },
		{ index: 152, value: false },
		{ index: 153, value: true },
		{ index: 154, value: false },
		{ index: 155, value: true },
		{ index: 156, value: false },
		{ index: 157, value: true },
		{ index: 158, value: true },
		{ index: 159, value: true },
		{ index: 160, value: true },
		{ index: 161, value: true },
		{ index: 162, value: true },
		{ index: 163, value: true },
		{ index: 164, value: false },
		{ index: 165, value: true },
		{ index: 166, value: true },
		{ index: 167, value: false },
		{ index: 168, value: true },
		{ index: 169, value: false },
		{ index: 170, value: true },
		{ index: 171, value: true },
		{ index: 172, value: true },
		{ index: 173, value: true },
		{ index: 174, value: true },
		{ index: 175, value: false },
		{ index: 176, value: false },
		{ index: 177, value: false },
		{ index: 178, value: false },
		{ index: 179, value: true },
		{ index: 180, value: false },
		{ index: 181, value: true },
		{ index: 182, value: true },
		{ index: 183, value: false },
		{ index: 184, value: true },
		{ index: 185, value: false },
		{ index: 186, value: true },
		{ index: 187, value: true },
		{ index: 188, value: true },
		{ index: 189, value: false },
		{ index: 190, value: true },
		{ index: 191, value: true },
		{ index: 192, value: false },
		{ index: 193, value: false },
		{ index: 194, value: false },
		{ index: 195, value: true },
		{ index: 196, value: true },
		{ index: 197, value: true },
		{ index: 198, value: false },
		{ index: 199, value: true },
		{ index: 200, value: false },
		{ index: 201, value: true },
		{ index: 202, value: false },
		{ index: 203, value: true },
		{ index: 204, value: true },
		{ index: 205, value: true },
		{ index: 206, value: false },
		{ index: 207, value: false },
		{ index: 208, value: false },
		{ index: 209, value: true },
		{ index: 210, value: true },
		{ index: 211, value: true },
		{ index: 212, value: true },
		{ index: 213, value: true },
		{ index: 214, value: false },
		{ index: 215, value: false },
		{ index: 216, value: true },
		{ index: 217, value: true },
		{ index: 218, value: true },
		{ index: 219, value: false },
		{ index: 220, value: true },
		{ index: 221, value: true },
		{ index: 222, value: true },
		{ index: 223, value: false },
		{ index: 224, value: true },
		{ index: 225, value: true },
		{ index: 226, value: true },
		{ index: 227, value: false },
		{ index: 228, value: false },
		{ index: 229, value: true },
		{ index: 230, value: false },
		{ index: 231, value: false },
		{ index: 232, value: true },
		{ index: 233, value: true },
		{ index: 234, value: true },
		{ index: 235, value: false },
		{ index: 236, value: true },
		{ index: 237, value: true },
		{ index: 238, value: true },
		{ index: 239, value: true },
		{ index: 240, value: true },
	],
	result: {
		/* 'novelty-seeking-(1)': 5,
		'novelty-seeking-(2)': 4,
		'novelty-seeking-(3)': 7,
		'novelty-seeking-(4)': 3, */
		'novelty-seeking': 19,
		/* 'harm-avoidance-(1)': 3,
		'harm-avoidance-(2)': 6,
		'harm-avoidance-(3)': 2,
		'harm-avoidance-(4)': 3, */
		'harm-avoidance': 14,
		/* 'reward-dependence-(1)': 10,
		'reward-dependence-(2)': 6,
		'reward-dependence-(3)': 4, */
		'reward-dependence': 20,
		persistance: 5,
		/* 'self-directedness-(1)': 6,
		'self-directedness-(2)': 4,
		'self-directedness-(3)': 1,
		'self-directedness-(4)': 4,
		'self-directedness-(5)': 6, */
		'self-directedness': 21,
		/* 'cooperativeness-(1)': 6,
		'cooperativeness-(2)': 7,
		'cooperativeness-(3)': 5,
		'cooperativeness-(4)': 9,
		'cooperativeness-(5)': 8, */
		'cooperativeness': 35,
		/* 'self-transcendence-(1)': 4,
		'self-transcendence-(2)': 4,
		'self-transcendence-(3)': 4, */
		'self-transcendence': 12,
		numb: 144,
		run: 113,
	},
};
